logging:
  pattern:
    console: "%d{MM-dd HH:mm:ss.SSS} |%X{x-request-id}| %5p [%t] %-40.40c{1.} : %m%n%ex"
    level:
      root: error
      com.icaroerasmo.seafood: info
      org.springframework: error