spring:
  data:
    mongodb:
      database: "seafood"
      uri: "mongodb://mongoadmin:secret@localhost:27017/seafood?directConnection=true&serverSelectionTimeoutMS=2000&authSource=admin"
logging:
  pattern:
    level:
      root: debug
      com.icaroerasmo.seafood: info
      org.springframework: debug
