de.flapdoodle.mongodb.embedded.version: 3.6.3
spring:
  data:
    mongodb:
      database: "seafood"
      uri: "mongodb://localhost:27017"

logging:
  pattern:
    level:
      root: debug
      com.icaroerasmo.seafood: info
      org.springframework: debug
